"""empty message

Revision ID: 105fb2e6b63e
Revises: f7c7a3cb4ff4
Create Date: 2025-06-14 11:10:14.394501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105fb2e6b63e'
down_revision = 'f7c7a3cb4ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
